config/routes.rb
Rails.application.routes.draw do
  get 'auth/starladder/callback', to: 'sessions#create'
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: %i[new create destroy]
  resource :home, only: :index

  resources :teams
  resources :tourneys, only: :index
  resources :participants, only: :show

  post 'tourneys/:id/join', to: 'tourneys#join_tourney', as: :join_tourney
  delete 'tourneys/:id/leave', to: 'tourneys#leave_tourney', as: :leave_tourney

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :team
  belongs_to :tourney

  validates_uniqueness_of :team_id, scope: :tourney_id
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :participants, dependent: :destroy
  has_many :tourneys, through: :participants
  belongs_to :user, foreign_key: 'team_owner_id'

  has_attached_file :logo, styles: { original: '200x200#', thumb: '100x100#' },
                           processors: [:thumbnail, :compression],
                           default_url: "images/missing.png"
  validates :name, presence: true
  validates_attachment_content_type :logo, content_type: ["image/jpg", "image/jpeg", "image/png"]

  def owner
    User.find_by_id(self.team_owner_id).nick
  end
end

app/models/tourney.rb
class Tourney < ApplicationRecord
  has_many :participants, dependent: :destroy
  has_many :teams, through: :participants

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_one :team, foreign_key: 'team_owner_id'

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.nick = auth.info.nick
      user.email = auth.info.email
      user.token = auth.credentials.token
      user.refresh_token = auth.credentials.refresh_token
      user.token_expires_at = auth.credentials.expires_at
      user.save!
    end
  end

  def has_team?
    Team.where(team_owner_id: self.id).present?
  end

  def user_team_joined?(tourney)
    if self.has_team?
      Participant.find_by(team_id: self.team.id, tourney_id: tourney.id).present?
    else
      false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_current_user

  def set_current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def check_logged_in
    if @current_user.blank?
      redirect_to root_path, notice: 'Not logged in user'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @teams = Team.all.order(created_at: :desc).paginate(page: params[:page], per_page: 20)
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_tourney

  def show
    @participants = @tourney.participants.all
  end

  private

  def set_tourney
    @tourney = Tourney.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path, alert: 'Tournament not found'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Welcome! You have been logged in'
    else
      redirect_to login_path, alert: 'Sorry, there was an error'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  def auth_failure
    redirect_to root_path
    p 'AUTHORIZATION FAILED'
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: %i[edit update destroy show]
  before_action :check_access, only: %i[edit destroy]

  def show; end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)
    @team.team_owner_id = @current_user.id
    if @team.save
      redirect_to root_path, notice: "Yor team #{@team.name} has been added"
    else
      render :new
    end
  end

  def edit; end

  def update
    if @team.update(team_params)
      redirect_to root_path, notice: "#{@team.name} has been updated successfully"
    else
      render :edit
    end
  end

  def destroy
    if @team.destroy
      redirect_to root_path, notice: "Your team #{@team.name} has been removed"
    else
      redirect_to root_path, alert: "Couldn't delete #{@team.name}"
    end
  end

  private

  def set_team
    @team = Team.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path, alert: "Couldn't find this team"
  end

  def check_access
    redirect_to root_path unless @current_user.id == @team.team_owner_id
  end

  def team_params
    params.require(:team).permit(:name, :logo)
  end
end

app/controllers/tourneys_controller.rb
class TourneysController < ApplicationController
  before_action :set_tourney, only: %i[join_tourney leave_tourney]
  before_action :set_team, only: %i[join_tourney leave_tourney]

  def index
    @tourneys = Tourney.all.includes(:participants).order(created_at: :desc).paginate(page: params[:page], per_page: 6)
  end

  def join_tourney
    participant = Participant.create(team_id: @team_id, tourney_id: @tourney.id)
    if participant.save
      redirect_to tourneys_path, notice: "Your joined #{@tourney.name}"
    else
      redirect_to tourneys_path, alert: "You have already joined the #{@tourney.name}"
    end
  end

  def leave_tourney
    participant = Participant.find_by(team_id: @team_id, tourney_id: @tourney.id)
    if participant.destroy
      redirect_to tourneys_path, notice: "Your leaved #{@tourney.name}"
    else
      redirect_to root_path, alert: "Couldn't leave #{@tourney.name}"
    end
  end

  private

  def set_team
    @team_id = Team.find_by(team_owner_id: @current_user.id).id
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path, alert: 'Team not found'
  end

  def set_tourney
    @tourney = Tourney.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path, alert: 'Tournament not found'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tourneys_helper.rb
module TourneysHelper
end

app/views/home/index.html.erb
<div class="container">
  <div class="page-header">
    <h1>Teams</h1>
    <% if @current_user && @current_user.has_team? == false %>
      <%= link_to new_team_path, class: 'btn btn-default' do %>
        Add Team
      <% end %>
    <% end %>
  </div>
  <div class="row">
    <% if @teams.present? %>
      <% @teams.each do |team| %>
        <div class="col-md-4">
          <div class="caption">
            <p><%= team.created_at.strftime("%d %B %Y %H:%M") %></p>
            <h3><%= team.name %></h3>
            <p>Owner: <%=team.owner %></p>
            <p><% if team.logo? %>
              <%= image_tag team.logo.url(:thumb), class: "rounded-img" %>
            <% else %>
              <%= image_tag 'missing.png', style: 'width:100px; height:100px;', class: "rounded-img" %>
            <% end %></p>
          </div>
          <div class="caption">
            <% if @current_user && @current_user.id == team.team_owner_id %>
              <%= link_to edit_team_path(team), class: 'btn btn-default' do %>
                Edit Team
              <% end %>
              <%= link_to team_path(team), method: :delete, data: { confirm: 'Are you sure you want to delete this team' }, class: 'btn btn-danger btn-sm' do %>
                Delete Team
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% else %>
      <h4>There are no Teams yet.</h4>
    <% end %>
  </div>
  <div class="container">
    <div class="row">
      <div class=".col-md-4"><%=will_paginate @teams, :renderer => BootstrapPagination::Rails %></div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tournament</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=render 'layouts/partials/flash_messages' %>
    <%=render "layouts/partials/header" %>
    <%= yield %>
  </body>
</html>

app/views/layouts/partials/_flash_messages.html.erb
<% if flash.any? %>
  <div class="notification">
    <% flash.each do |key, msg| %>
      <%= content_tag :div, msg, class: [key.to_s], id: "notification" %>
    <% end %>
  </div>
<% end %>

app/views/layouts/partials/_form_error_messages.html.erb
<% if object.errors.any? %>
    <ul class="errors">
      <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
    </ul>
<% end %>

app/views/layouts/partials/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header pull-left">
      <a class="btn btn-success navbar-btn" href='/'>Home</a>
      <a class="btn btn-success navbar-btn" href='/tourneys'>Tournaments</a>
    </div>
    <div class="navbar-header pull-right">
      <% if @current_user %>
        <p class="navbar-text">Signed in as <strong><%=@current_user.nick %></strong></p>
        <a class="btn btn-default navbar-btn" href='/signout'>Logout</a>
      <% else %>
        <a class="btn btn-default navbar-btn" href='auth/starladder'>Sign in</a>
      <% end %>
    </div>
  </div>
</nav>

app/views/participants/show.html.erb
<div class="container">
  <div class="page-header">
    <h1><%=@tourney.name %> tournament Participants</h1>
  </div>
  <div class="row">
    <% if @tourney.participants.present? %>
    <h4>Participants count: <%=@tourney.participants.count %></h4>
      <% @tourney.participants.each_with_index do |participant, i| %>
        <div class="col-md-4">
          <div class="caption">
            <h3><%= (i+1) %></h3>
            <p>Joined to <%=@tourney.name %> tournament at <%=participant.created_at.strftime("%d %B %Y %H:%M") %></p>
            <% if participant.team.logo? %>
              <%= image_tag participant.team.logo.url(:thumb), style: :thumb, class: "rounded-img" %>
            <% else %>
              <%= image_tag 'missing.png', style: 'width:100px; height:100px;', class: "rounded-img" %>
            <% end %>
            <h3><%=participant.team.name %></h3>
            <p>Owner: <%=participant.team.owner %></p>
          </div>
        </div>
      <% end %>
    <% else %>
      <h4>There are no Participants yet.</h4>
    <% end %>
  </div>
</div>

app/views/tourneys/index.html.erb
<div class="container">
  <div class="page-header">
    <h1>Tournaments</h1>

  </div>
  <div class="row">
    <% if @tourneys.present? %>
      <% @tourneys.each do |tourney| %>
        <div class="panel panel-default">
          <div class="panel-body">
            <h3><%=tourney.name %></h3>
            <p class="party-count">Participants: <%=tourney.participants.count %></p>
            <p class="party"><%= link_to participant_path(tourney), class: 'btn btn-default' do %>
              Show all participants
            <% end %></p>
          </div>
          <div class="caption">
            <% if @current_user && @current_user.user_team_joined?(tourney) == true %>
              <%= link_to leave_tourney_path(tourney), method: :delete, data: { confirm: 'Are you sure you want to leave this tournament' }, class: 'btn btn-danger btn' do %>
                Leave Tournament
              <% end %>
            <% elsif @current_user && @current_user.has_team? %>
              <%= link_to join_tourney_path(tourney), method: :post, class: 'btn btn-success' do %>
                Join Tournament
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% else %>
      <h4>There are no Tournaments yet.</h4>
    <% end %>
  </div>
  <div class="container">
    <div class="row">
      <div class=".col-md-4"><%=will_paginate @teams, :renderer => BootstrapPagination::Rails %></div>
    </div>
  </div>
</div>